server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
    fallback-to-system-locale: false
  security:
    user:
      name: username
      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
